### ISSUE TITLE
[FEATURE REQUESTS] - Activiter du Serveur

### ISSUE THREAD

**Issue by Dremos79C** [CraftMyWebsite/theme-nethercraft#1]
# 🛠️ Demandes de fonctionnalités

## Description de la fonctionnalité

Je propose de permettre d'afficher l'état du serveur si besoin au dessus du nombre de joueur en ligne
Afin de savoir si le serveur est en ligne, hors ligne, en maintenance, en test, ect...

## Utilisation prévue

L'utilisateur n'aura qu'a selectionner si il souhaite noter que son serveur est en ligne, hors ligne, en maintenance, en test, ect...
Biensur il paurait aussi ne pas vouloir de la fonctionnaliter et la désactiver

## Justification

Je donne l'exemple de moi actuelement, mon serveur est en maintenance car je fait une grosse mise a jour dessus et que je refait completement le site donc j'aurais aimer que les visiteurs ne voient pas que le faite qui est 0 personnes sur le serveur mais que c'st jusifier car le serveur est en maintenance.

## Alternatives possibles

Aucune

## Impact sur le projet

A part un visuel different aucun changement est attendue.

## Captures d'écran ou maquettes (facultatif)

Je n'ai rien pour illustrer.

## Ressources supplémentaires

Je n'ai rien en plus.

**Comment by Zomblard** [comment]
Added : https://github.com/CraftMyWebsite/theme-nethercraft/commit/105f7b108e90819fb9b9e9366eedbf6a25312628
