### ISSUE TITLE
[FEATURE REQUESTS] - Position des images section what to do

### ISSUE THREAD

**Issue by Dremos79C** [CraftMyWebsite/theme-nethercraft#2]
🛠️ Demandes de fonctionnalités
Description de la fonctionnalité
Pouvoir avoir son image pleine page dans la case même en changant le nombreux de case.

Utilisation prévue
Pouvoir voir l'image complete dans la case sans devoir modifier notre image a chaque fois et qu'elle soit redimentionner peu importe le support
que sur pc elle soit net mais quand ont passe sur telephone qu'elle ne soit pas deformer.

Petite note suplémentaire
Pouvoir la possibiliter d'apliquer un leger zoom ou dé zoom pour que cela ajoute du dinamisme a la page

Alternatives possibles
Avoir la taille exacte en pixel des cases afin de modifier son image a la taille demande
et avoir une dimention maximum afin que l'image ne soit pas deformer

**Comment by Zomblard** [comment]
_Pouvoir avoir son image pleine page dans la case même en changant le nombreux de case._
>>> C'est déjà le cas (il suffit de modifier le nombre de colonnes)

Added : https://github.com/CraftMyWebsite/theme-nethercraft/commit/3fdbbad8588c55d00eac75fccc2e8b298fc5fb5c
